//
//  StyleKitName.h
//  PaintCodeWorkflow
//
//  Created by Carl Jahn + Florian Bachmann on 14.06.15.
//  Copyright (c) 2015 Flori + Carl. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Drawing Methods
+ (void)drawWLANWithFrame: (CGRect)frame outer: (BOOL)outer inner: (BOOL)inner;
+ (void)drawClockWithFrame: (CGRect)frame refresh: (CGFloat)refresh timeinterval: (CGFloat)timeinterval;

@end
